M48
; DRILL file {KiCad 9.0.6} date 2026-03-03T09:40:08+1100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-03T09:40:08+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X78.3Y-64.785
X78.3Y-70.565
T2
X101.2Y-46.405
X109.3Y-131.67
X109.6Y-46.405
M30
